/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kbt;

import javax.security.auth.login.LoginException;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;

public class Main {

    public static JDA instance;

    public static void main(String[] args) {
        try {
            JDABuilder jdaBuilder = JDABuilder.createDefault("token");
            instance = jdaBuilder.build();
        } catch (LoginException e) {
            e.printStackTrace();
        }

    }
}
